alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.192-168-49-2.nip.io
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
 
grafana:
  serviceMonitor:
    labels:
      release: kps
  ingress:
    enabled: true
    hosts:
      - grafana.192-168-49-2.nip.io
  persistence:
    enabled: true
    size: 2Gi
  adminPassword: admin

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.192-168-49-2.nip.io
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi 

