data:
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs

  resource.customizations.health.monitoring.coreos.com_Prometheus: |
    found_status = false
    hs={ status = "Progressing", message = "Waiting for initialization" }
    if obj.status ~= nil then
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do

          if condition.type == "Available" then
            found_status = true
            if condition.status ~= "True" then
              if condition.reason == "SomePodsNotReady" then
                hs.status = "Progressing"
              else
                hs.status = "Degraded"
              end
              hs.message = condition.message or condition.reason
            end
            if condition.status == "True" then
              hs.status = "Healthy"
              hs.message = "All instances are available"
            end
          end
        end
      end
    end
    if not found_status then
      hs={ status = "Healthy", message = "Ignoring Prometheus Health Check" }
    end
    return hs

