apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-crds
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: kube-prometheus-stack-35.4.2
    path: charts/kube-prometheus-stack/crds
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - Replace=true
