apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: monitoring
  namespace: argocd
spec:
  destination:
    name: cluster1-node1
    namespace: cattle-monitoring-system
  project: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: http://charts.rancher.io/
    chart: rancher-monitoring
    targetRevision: 100.1.3+up19.0.3
    helm:
      releaseName: rancher-monitoring
      skipCrds: true
      values: |-
        global:
          cattle:
            clusterId: c-l6mmz
            clusterName: cluster1
            rkePathPrefix: ''
            rkeWindowsPathPrefix: ''
            systemDefaultRegistry: ''
            systemProjectId: p-8pt65
            url: https://rancher.mydomain.net
          systemDefaultRegistry: ''
        ingressNginx:
          enabled: true
        prometheus:
          prometheusSpec:
            evaluationInterval: 1m
            retentionSize: 50GiB
            scrapeInterval: 1m
        rkeControllerManager:
          enabled: true
        rkeEtcd:
          enabled: true
        rkeProxy:
          enabled: true
        rkeScheduler:
          enabled: true

